[package]
name = "anvilml-scheduler"
version = "0.1.6"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anvilml-worker = { path = "../anvilml-worker" }
anvilml-registry = { path = "../anvilml-registry" }
anvilml-artifacts = { path = "../anvilml-artifacts" }
anvilml-core = { path = "../anvilml-core" }
anvilml-hardware = { path = "../anvilml-hardware" }
serde_json = "1"
thiserror = "2.0.18"

[features]
mock-hardware = ["anvilml-hardware/mock-hardware"]
